#!/bin/sh

# link this by running `ln -fs ../../pre-commit .git/hooks/pre-commit`

# poor man's JSON site API:
# cp harp.json public/json

# nice if you use different surge accounts (work, play, etc.)
# USE WITH CAUTION AND ONLY ON SECURED SYSTEMS
# add email and password to .auth ENSURE .auth IS IN .gitignore
if [ -e .auth ]; then
  surge logout
  cat .auth | surge login
fi

harp compile
[ $? -ne 0 ] && exit 1

surge www
[ $? -ne 0 ] && exit 1
exit 0
